#src/Vendor/BundleName/Resources/config/services.yml

parameters:
    vendor_security.authentication_handler: UserBundle\Controller\AuthenticationHandler

services:
    authentication_handler:
        class:  "%vendor_security.authentication_handler%"
        arguments:  ['@router']
        tags:
            - { name: 'monolog.logger', channel: 'security' }