<?php

namespace TimetrackerBundle\Repository;

/**
 * CalendarMonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarMonthRepository extends \Doctrine\ORM\EntityRepository
{
}
