<?php

namespace TimetrackerBundle\Repository;

/**
 * TrackedDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackedDayRepository extends \Doctrine\ORM\EntityRepository
{
}
