<?php

namespace TimetrackerBundle\Repository;

/**
 * TrackedProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackedProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
